### ISSUE TITLE
drupalConsole issue when building project with composer

### ISSUE THREAD

**Issue by irmantasp** [wodby/docker4drupal#86] opened 2017-01-26 22:11 UTC
Situation I encountered is as follows:
I download drupal 8 using composer (by default it already includes drupal console as dependency).
I start docker-compose using this container.
when I try to use drupal console command it thows bunch of errors due to the dublicated installation. 
Would it be possible to make sure to avoid this problem if mounted directory contains vendor/bin/drupal directory?

**Comment by PavelPrischepa** [comment] 2017-01-31 12:08
Could you provide steps to reproduce the problem?

**Comment by michaelpetri** [comment] 2017-02-02 21:57
I'm running into the same(?) or a familiar problem. I also use the composer to download drupal 8.

When i run:
`docker-compose exec php drupal [command]`

I receive the following error:
`TypeError: Argument 1 passed to Drupal\Console\Core\Utils\TwigRenderer::__construct() must be an instance of Drupal\Console\Core\Utils\TranslatorManagerInterface, instance of Drupal\Console\Utils\TranslatorManager given in /var/www/html/vendor/drupal/console-core/src/Utils/TwigRenderer.php on line 43 #0 [internal function]: Drupal\Console\Core\Utils\TwigRenderer->__construct(Object(Drupal\Console\Utils\TranslatorManager), Object(Drupal\Console\Core\Utils\StringConverter))
#1 phar:///usr/local/bin/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(928): ReflectionClass->newInstanceArgs(Array)
#2 phar:///usr/local/bin/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(468): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'console.rendere...')
#3 /var/www/html/vendor/drupal/console/src/Bootstrap/Drupal.php(126): Symfony\Component\DependencyInjection\ContainerBuilder->get('console.rendere...')
#4 /var/www/html/vendor/drupal/console/bin/drupal.php(49): Drupal\Console\Bootstrap\Drupal->boot(false)
#5 phar:///usr/local/bin/drupal/src/Utils/Launcher.php(28): include_once('/var/www/html/v...')
#6 phar:///usr/local/bin/drupal/bin/drupal.php(87): Drupal\Console\Utils\Launcher->launch('/var/www/html')
#7 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#8 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#9 {main}
TypeError: Argument 1 passed to Drupal\Console\Core\Utils\TwigRenderer::__construct() must be an instance of Drupal\Console\Core\Utils\TranslatorManagerInterface, instance of Drupal\Console\Utils\TranslatorManager given in Drupal\Console\Core\Utils\TwigRenderer->__construct() (line 43 of /var/www/html/vendor/drupal/console-core/src/Utils/TwigRenderer.php).
`

I read on other sources this could be caused by an outdated console version so i tried composer update.

In composer.json i require 
`"drupal/console": "~1.0"` 
and the composer.lock says: 
`"name": "drupal/console",
"version": "1.0.0-rc15",`

On an other source i read this error occurs only on php7?! 
I will change the php container to php5x tomorrow and share my results.

**Comment by michaelpetri** [comment] 2017-02-03 08:57
Hi,

the problem is the console version provided by the docker image. 
If i call the composer version directly everything works fine for me.

`docker-compose exec --user 82 php /var/www/html/vendor/bin/drupal list`

Best regards
Michael

**Comment by brilsergei** [comment] 2017-02-07 18:36
Had same issue. I just did next and it helped me
`docker-compose exec php sh`
then
`
cd ../
drupal self-update
`
But probably it works only until you rebuild container.

**Comment by PavelPrischepa** [comment] 2017-02-08 03:43
@michaelpetri @brilsergei What is version of PHP container do you use? What version of drupal/console in container and in /var/www/html/vendor/bin/drupal?

**Comment by michaelpetri** [comment] 2017-02-08 08:58
I'm using `wodby/drupal-php:7.0-1.0.0`

And with my last solution i also run into some errors. At least this worked for me:
`docker exec -it [container_name] /var/www/html/vendor/bin/drupal <command>`

**Comment by irmantasp** [comment] 2017-02-22 14:09
Any news on this one?

**Comment by gambry** [comment] 2017-03-06 15:35
I confirm the issue, although my error was:

> PHP Fatal error:  Cannot use Drupal\Console\Core\Bootstrap\DrupalConsoleCore as DrupalConsoleCore because the name is already in use in /var/www/html/vendor/drupal/console/src/Bootstrap/Drupal.php on line 11
> 
> Fatal error: Cannot use Drupal\Console\Core\Bootstrap\DrupalConsoleCore as DrupalConsoleCore because the name is already in use in /var/www/html/vendor/drupal/console/src/Bootstrap/Drupal.php on line 11

And using @michaelpetri solution (specifying the vendor/bin/drupal absolute path) works.

**Comment by csandanov** [comment] 2017-03-08 12:05
In a new 2.0.0 version composer, drush and console now installed globally for www-data user

**Comment by csandanov** [comment] 2017-03-10 05:37
It seems drupal console installed in a new way has no issues, I'm closing this issue.

**Closed by csandanov** 2017-03-10 05:37 UTC
Labels: bug
